export const GET_STOCK_DATA = 'GET_STOCK_DATA';
export const UPDATE_BUY_PRICES_INDEX = 'UPDATE_BUY_PRICES_INDEX';
export const UPDATE_STOP_LOSS_RATES_INDEX = 'UPDATE_STOP_LOSS_RATES_INDEX';
export const UPDATE_PROTOCOL_STATUS = 'UPDATE_PROTOCOL_STATUS';
export const GET_STOCK_SUGGEST = 'GET_STOCK_SUGGEST';
export const UPDATE_CURRENT_STOCK_CODE = 'UPDATE_CURRENT_STOCK_CODE';
