export const GET_STOCK_DATA = 'GET_STOCK_DATA';
export const UPDATE_BUY_PRICES_INDEX = 'UPDATE_BUY_PRICES_INDEX';
export const UPDATE_STOP_LOSS_RATES_INDEX = 'UPDATE_STOP_LOSS_RATES_INDEX';
export const UPDATE_PROTOCOL_STATUS = 'UPDATE_PROTOCOL_STATUS';
export const GET_STOCK_SUGGEST = 'GET_STOCK_SUGGEST';

// Sell
export const GET_POSITION_DATA = 'GET_POSITION_DATA';
export const SELL_OUT_STOCK = 'SELL_OUT_STOCK';